title: sacenox logs
description: terminal notes from the edge
url: ""
baseurl: ""
markdown: kramdown
permalink: /posts/:title/
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed
