title: sacenox logs
description: terminal notes from the edge
url: "https://sacenox.github.io"
baseurl: ""
markdown: kramdown
permalink: /posts/:title/
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
author:
  name: sacenox
defaults:
  - scope:
      path: ""
    values:
      image: "https://avatars.githubusercontent.com/u/33629225?v=4"
social:
  links:
    - "https://github.com/sacenox"
    - "https://gitlab.com/xonecas"
    - "https://github.com/xonecas"
sass:
  sass_dir: _sass
  style: compressed
